version: '3'
tasks:
  build:
    cmds:
      - echo $GOOS
      - go build -o goHelper main.go
    env:
      GO111MODULE: 'on'
      GOPROXY: 'https://goproxy.cn,direct'
      GOOS: 'linux'
      GOARCH: 'amd64'
      CGO_ENABLED: '0'
